"""pay schedules and periods

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-22 19:40:11.547918

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pay_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.String(length=16), nullable=False),
        sa.Column("anchor_date", sa.Date(), nullable=True),
        sa.Column("day_of_month_1", sa.Integer(), nullable=True),
        sa.Column("day_of_month_2", sa.Integer(), nullable=True),
        sa.Column("weekend_rule", sa.String(length=32), server_default="none", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "frequency IN ('weekly', 'biweekly', 'semimonthly', 'monthly')",
            name="ck_pay_schedules_frequency",
        ),
        sa.CheckConstraint(
            "weekend_rule IN ('none', 'previous_business_day', 'next_business_day')",
            name="ck_pay_schedules_weekend_rule",
        ),
        sa.CheckConstraint(
            "day_of_month_1 IS NULL OR day_of_month_1 BETWEEN 1 AND 31",
            name="ck_pay_schedules_day_1",
        ),
        sa.CheckConstraint(
            "day_of_month_2 IS NULL OR day_of_month_2 BETWEEN 1 AND 31",
            name="ck_pay_schedules_day_2",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pay_schedules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pay_schedules_effective_from"), ["effective_from"], unique=True
        )

    op.create_table(
        "pay_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("is_transition", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("end_date >= start_date", name="ck_pay_periods_order"),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["pay_schedules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pay_periods", schema=None) as batch_op:
        batch_op.create_index("ix_pay_periods_range", ["start_date", "end_date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_pay_periods_schedule_id"), ["schedule_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_pay_periods_start_date"), ["start_date"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pay_periods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pay_periods_start_date"))
        batch_op.drop_index(batch_op.f("ix_pay_periods_schedule_id"))
        batch_op.drop_index("ix_pay_periods_range")

    op.drop_table("pay_periods")
    with op.batch_alter_table("pay_schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pay_schedules_effective_from"))

    op.drop_table("pay_schedules")
    # ### end Alembic commands ###
