"""accounts categories payees

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-23 15:21:50.457489

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120, collation="NOCASE"), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("on_budget", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("opening_balance_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.Column("institution", sa.String(length=120), nullable=True),
        sa.Column("last4", sa.String(length=4), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_closed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "valuation_mode", sa.String(length=16), server_default="transactions", nullable=False
        ),
        sa.Column("apr_bps", sa.Integer(), nullable=True),
        sa.Column("min_payment_cents", sa.Integer(), nullable=True),
        sa.Column("payment_due_day", sa.Integer(), nullable=True),
        sa.Column("low_balance_alert_cents", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('checking', 'savings', 'credit_card', 'cash', 'loan', "
            "'mortgage', 'investment', 'other_asset', 'other_liability')",
            name="ck_accounts_type",
        ),
        sa.CheckConstraint(
            "valuation_mode IN ('transactions', 'manual')", name="ck_accounts_valuation_mode"
        ),
        sa.CheckConstraint("apr_bps IS NULL OR apr_bps >= 0", name="ck_accounts_apr_bps"),
        sa.CheckConstraint(
            "payment_due_day IS NULL OR payment_due_day BETWEEN 1 AND 31",
            name="ck_accounts_payment_due_day",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_name"), ["name"], unique=True)

    op.create_table(
        "category_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120, collation="NOCASE"), nullable=False),
        sa.Column("kind", sa.String(length=16), server_default="expense", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_hidden", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('expense', 'income')", name="ck_category_groups_kind"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("category_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_category_groups_name"), ["name"], unique=True)

    op.create_table(
        "account_valuations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("balance_cents", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "date", name="uq_account_valuations_account_date"),
    )
    with op.batch_alter_table("account_valuations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_account_valuations_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120, collation="NOCASE"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_hidden", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_sinking_fund", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("default_planned_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["category_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "name", name="uq_categories_group_name"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_categories_group_id"), ["group_id"], unique=False)

    op.create_table(
        "payees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120, collation="NOCASE"), nullable=False),
        sa.Column("default_category_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["default_category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payees", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payees_default_category_id"), ["default_category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_payees_name"), ["name"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payees_name"))
        batch_op.drop_index(batch_op.f("ix_payees_default_category_id"))

    op.drop_table("payees")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_group_id"))

    op.drop_table("categories")
    with op.batch_alter_table("account_valuations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_valuations_account_id"))

    op.drop_table("account_valuations")
    with op.batch_alter_table("category_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_groups_name"))

    op.drop_table("category_groups")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_name"))

    op.drop_table("accounts")
    # ### end Alembic commands ###
