"""transactions and splits

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-23 16:50:24.789535

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("payee_id", sa.Integer(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="uncleared", nullable=False),
        sa.Column("check_number", sa.String(length=32), nullable=True),
        sa.Column("transfer_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('uncleared', 'cleared', 'reconciled')", name="ck_transactions_status"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payee_id"],
            ["payees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index("ix_transactions_account_date", ["account_id", "date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_transactions_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index("ix_transactions_date", ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_transactions_payee_id"), ["payee_id"], unique=False)
        batch_op.create_index("ix_transactions_transfer_id", ["transfer_id"], unique=False)

    op.create_table(
        "transaction_splits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transaction_splits", schema=None) as batch_op:
        batch_op.create_index("ix_transaction_splits_category", ["category_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_transaction_splits_transaction_id"), ["transaction_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction_splits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_splits_transaction_id"))
        batch_op.drop_index("ix_transaction_splits_category")

    op.drop_table("transaction_splits")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_transfer_id")
        batch_op.drop_index(batch_op.f("ix_transactions_payee_id"))
        batch_op.drop_index("ix_transactions_date")
        batch_op.drop_index(batch_op.f("ix_transactions_account_id"))
        batch_op.drop_index("ix_transactions_account_date")

    op.drop_table("transactions")
    # ### end Alembic commands ###
