"""period plans

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24 00:21:04.837900

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "period_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pay_period_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("planned_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("planned_cents >= 0", name="ck_period_plans_planned_non_negative"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pay_period_id"], ["pay_periods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pay_period_id", "category_id", name="uq_period_plans_period_category"),
    )
    with op.batch_alter_table("period_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_period_plans_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_period_plans_pay_period_id"), ["pay_period_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("period_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_period_plans_pay_period_id"))
        batch_op.drop_index(batch_op.f("ix_period_plans_category_id"))

    op.drop_table("period_plans")
    # ### end Alembic commands ###
