"""subscriptions

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-24 02:54:41.881440

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("payee_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.String(length=16), nullable=False),
        sa.Column("interval_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("interval_unit", sa.String(length=8), nullable=True),
        sa.Column("anchor_date", sa.Date(), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("auto_post", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("remind_days_before", sa.Integer(), server_default="3", nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "frequency IN ('weekly', 'biweekly', 'monthly', 'quarterly', 'semiannual', "
            "'annual', 'custom')",
            name="ck_subscriptions_frequency",
        ),
        sa.CheckConstraint(
            "interval_unit IS NULL OR interval_unit IN ('day', 'week', 'month')",
            name="ck_subscriptions_interval_unit",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'cancelled')", name="ck_subscriptions_status"
        ),
        sa.CheckConstraint("amount_cents > 0", name="ck_subscriptions_amount_positive"),
        sa.CheckConstraint("interval_count >= 1", name="ck_subscriptions_interval_count"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["payee_id"], ["payees.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscriptions_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_subscriptions_payee_id"), ["payee_id"], unique=False)

    op.create_table(
        "subscription_occurrences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="upcoming", nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('upcoming', 'paid', 'skipped')", name="ck_occurrences_status"
        ),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subscription_id", "due_date", name="uq_occurrences_subscription_due"),
    )
    with op.batch_alter_table("subscription_occurrences", schema=None) as batch_op:
        batch_op.create_index("ix_occurrences_due_date", ["due_date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_subscription_occurrences_subscription_id"),
            ["subscription_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subscription_occurrences_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "subscription_price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subscription_price_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscription_price_history_subscription_id"),
            ["subscription_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription_price_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscription_price_history_subscription_id"))

    op.drop_table("subscription_price_history")
    with op.batch_alter_table("subscription_occurrences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscription_occurrences_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_subscription_occurrences_subscription_id"))
        batch_op.drop_index("ix_occurrences_due_date")

    op.drop_table("subscription_occurrences")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_payee_id"))
        batch_op.drop_index(batch_op.f("ix_subscriptions_category_id"))

    op.drop_table("subscriptions")
    # ### end Alembic commands ###
