"""notifications

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 03:44:38.068277

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("ref_key", sa.String(length=120), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('bill_due', 'bill_overdue', 'low_balance', 'auto_post', 'backup_failed', "
            "'test')",
            name="ck_notification_log_kind",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "ref_key", name="uq_notification_log_kind_ref"),
    )
    with op.batch_alter_table("notification_log", schema=None) as batch_op:
        batch_op.create_index("ix_notification_log_sent_at", ["sent_at"], unique=False)

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("low_balance_since", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("low_balance_since")

    with op.batch_alter_table("notification_log", schema=None) as batch_op:
        batch_op.drop_index("ix_notification_log_sent_at")

    op.drop_table("notification_log")
    # ### end Alembic commands ###
