"""imports and rules

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-24 04:05:18.852390

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120, collation="NOCASE"), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("delimiter", sa.String(length=1), nullable=False),
        sa.Column("has_header", sa.Boolean(), nullable=False),
        sa.Column("skip_rows", sa.Integer(), nullable=False),
        sa.Column("date_column", sa.Integer(), nullable=False),
        sa.Column("date_format", sa.String(length=16), nullable=False),
        sa.Column("amount_mode", sa.String(length=16), nullable=False),
        sa.Column("amount_column", sa.Integer(), nullable=True),
        sa.Column("debit_column", sa.Integer(), nullable=True),
        sa.Column("credit_column", sa.Integer(), nullable=True),
        sa.Column("invert_sign", sa.Boolean(), nullable=False),
        sa.Column("description_column", sa.Integer(), nullable=False),
        sa.Column("memo_column", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_mode IN ('single', 'debit_credit')", name="ck_import_profiles_mode"
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("imported_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("parse_errors", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("format IN ('csv', 'ofx', 'qfx')", name="ck_import_batches_format"),
        sa.CheckConstraint(
            "status IN ('staged', 'committed', 'undone')", name="ck_import_batches_status"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["profile_id"], ["import_profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_batches_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("match_field", sa.String(length=16), nullable=False),
        sa.Column("match_type", sa.String(length=16), nullable=False),
        sa.Column("match_value", sa.Text(), nullable=False),
        sa.Column("amount_min_cents", sa.Integer(), nullable=True),
        sa.Column("amount_max_cents", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("set_payee_id", sa.Integer(), nullable=True),
        sa.Column("set_category_id", sa.Integer(), nullable=True),
        sa.Column("set_memo", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("match_field IN ('description', 'memo')", name="ck_rules_field"),
        sa.CheckConstraint(
            "match_type IN ('contains', 'starts_with', 'equals', 'regex')", name="ck_rules_type"
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["set_category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["set_payee_id"], ["payees.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "import_staged_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("raw_description", sa.Text(), nullable=False),
        sa.Column("raw_memo", sa.Text(), nullable=False),
        sa.Column("import_key", sa.String(length=64), nullable=False),
        sa.Column("payee_id", sa.Integer(), nullable=True),
        sa.Column("new_payee_name", sa.String(length=120), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("disposition", sa.String(length=8), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column("matched_transaction_id", sa.Integer(), nullable=True),
        sa.Column("applied_rule_id", sa.Integer(), nullable=True),
        sa.Column("bill_occurrence_id", sa.Integer(), nullable=True),
        sa.Column("link_bill", sa.Boolean(), nullable=False),
        sa.Column("created_transaction_id", sa.Integer(), nullable=True),
        sa.Column("previous_status", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "disposition IN ('import', 'skip', 'match')", name="ck_import_rows_disposition"
        ),
        sa.ForeignKeyConstraint(["applied_rule_id"], ["rules.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["batch_id"], ["import_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["bill_occurrence_id"], ["subscription_occurrences.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["created_transaction_id"], ["transactions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["matched_transaction_id"], ["transactions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["payee_id"], ["payees.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_staged_rows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_staged_rows_batch_id"), ["batch_id"], unique=False
        )

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("import_batch_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("import_key", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("imported_description", sa.Text(), nullable=True))
        batch_op.create_index(
            "ix_transactions_account_import_key", ["account_id", "import_key"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_transactions_import_batch_id_import_batches",
            "import_batches",
            ["import_batch_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(
            "fk_transactions_import_batch_id_import_batches", type_="foreignkey"
        )
        batch_op.drop_index("ix_transactions_account_import_key")
        batch_op.drop_column("imported_description")
        batch_op.drop_column("import_key")
        batch_op.drop_column("import_batch_id")

    with op.batch_alter_table("import_staged_rows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_staged_rows_batch_id"))

    op.drop_table("import_staged_rows")
    op.drop_table("rules")
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_batches_account_id"))

    op.drop_table("import_batches")
    op.drop_table("import_profiles")
    # ### end Alembic commands ###
