"""reconciliations

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-24 04:45:36.364141

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("statement_date", sa.Date(), nullable=False),
        sa.Column("statement_balance_cents", sa.Integer(), nullable=False),
        sa.Column("adjustment_transaction_id", sa.Integer(), nullable=True),
        sa.Column("completed_by", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reconciliations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reconciliations_account_date", ["account_id", "statement_date"], unique=False
        )

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reconciliation_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_transactions_reconciliation_id"), ["reconciliation_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_transactions_reconciliation_id_reconciliations",
            "reconciliations",
            ["reconciliation_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_transactions_reconciliation_id_reconciliations", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_transactions_reconciliation_id"))
        batch_op.drop_column("reconciliation_id")

    with op.batch_alter_table("reconciliations", schema=None) as batch_op:
        batch_op.drop_index("ix_reconciliations_account_date")

    op.drop_table("reconciliations")
    # ### end Alembic commands ###
