"""net worth and debt plan

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-24 23:09:49.589428

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "debt_plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(length=16), nullable=False),
        sa.Column("extra_monthly_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("custom_order", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "strategy IN ('snowball', 'avalanche', 'custom')", name="ck_debt_plan_strategy"
        ),
        sa.CheckConstraint("extra_monthly_cents >= 0", name="ck_debt_plan_extra"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("closed_on", sa.Date(), nullable=True))

    # ### end Alembic commands ###
    # Accounts closed before this column existed: their last update is the best date we have
    # (D-094).
    op.execute("UPDATE accounts SET closed_on = date(updated_at) WHERE is_closed = 1")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("closed_on")

    op.drop_table("debt_plan")
    # ### end Alembic commands ###
